#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Set a default shell prompt:
#PS1='[\u@\h \W]\$ '
PS1='\u@\h:\w\$ '
PS2='> '

if [ -f ~/.profile ]
then
    source ~/.profile
fi
