#!/bin/bash

export EDITOR=emacs
export TERMINAL=xfce4-terminal
CDPATH=$CDPATH:/mnt/

# Aliases
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -la'

# git stuff
alias gia='git add'
alias gib='git branch'
alias gic='git commit'
alias gid='git diff'
alias gif='git fetch -p'
alias gih='git stash'
alias gik='git checkout'
alias gil='git log'
alias gim='git merge'
alias gip='git cherry-pick'
alias gipl='git pull'
alias gips='git push'
alias gir='git rebase'
alias gis='git status'
